# Generated by Django 4.2.21 on 2026-08-20 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_course_prerequisites'),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('quiz', 'Quiz'), ('assignment', 'Assignment'), ('midterm', 'Midterm Exam'), ('final', 'Final Exam'), ('attendance', 'Attendance & Conduct'), ('project', 'Practical Project')], default='assignment', max_length=20)),
                ('weight_percentage', models.DecimalField(decimal_places=1, default=15.0, max_digits=4)),
                ('score_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_grades', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course', 'category', 'created_at'],
            },
        ),
    ]
