# Generated by Django 4.2.21 on 2026-08-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='academic_standing',
            field=models.CharField(default='Good Standing', max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, default=3.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='credits_completed',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='financial_hold',
            field=models.BooleanField(default=False),
        ),
    ]
