# Generated by Django 4.2.21 on 2026-07-28 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus', models.CharField(max_length=180)),
                ('next_step', models.CharField(max_length=240)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('monitoring', 'Monitoring'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_intervention_plans', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_intervention_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CounselingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('met_at', models.DateTimeField()),
                ('notes', models.TextField()),
                ('follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_counseling_logs', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_counseling_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-met_at'],
            },
        ),
    ]
